feat: Write one-shot CLI
p2p-industries/hyveos pull request #59
Opened 2024-12-07 16:35 UTC by Lxixnxuxs

Write a complete one-shot CLI.
Closes #12

2025-01-10 22:05 UTC, umgefahren approved these changes
Minor things but otherwise LGTM :rocket:

Curious about @Zollerboy1  opinion

2025-01-10 22:38 UTC, Lxixnxuxs commented on crates/hyvectl/src/main.rs
> +#[allow(clippy::never_loop)]
Did you run clippy? for me `cargo clippy --package hyvectl --bin hyvectl  --target aarch64-unknown-linux-gnu --no-default-features -- -D warnings ` fails with never_loop

2025-01-10 23:15 UTC, umgefahren commented on crates/hyvectl/src/main.rs
> +#[allow(clippy::never_loop)]
okay, keep it. I want to transition to the expect macro anyway

2025-01-11 04:23 UTC, Zollerboy1 requested changes

2025-01-11 04:23 UTC, Zollerboy1 commented on crates/hyvectl/src/out.rs
> +                let s = serde_json::to_string_pretty(&Value::Object(obj))?;
I would also provide different outputs here depending on whether we're in a TTY or not. E.g. non-tty output should be `serve_json::to_string` (so without any formatting) and TTY output could be `colored_json::write_colored_json` (needs the `colored_json` dependency but looks very nice in return).

2025-01-11 04:23 UTC, Zollerboy1 commented on sdks/rust/src/services/req_resp.rs
> +
```suggestion

    #[doc(hidden)]
```

2025-01-11 19:30 UTC, Lxixnxuxs commented
I rolled back the json coloring, because [colored_json](https://github.com/ctron/colored_json) is under a EPL2 which is weak copyleft, and the only other json coloring crate I found under a Apache/MIT [json-color](https://github.com/saghm/json-color) has a weird interface, I do not want to implement now

2025-01-11 21:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/p2p-industries/hyveos?pullRequest=59) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/p2p-industries/hyveos?pullRequest=59) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/p2p-industries/hyveos?pullRequest=59) it.</sub>

2025-01-12 00:59 UTC, Zollerboy1 approved these changes

2025-01-12 01:01 UTC, merged